@startuml fire (id=Fire)

state Fire_Emergency as "Fire Emergency"#df2c0c {
    state Key_Questions as "Key Questions" #C3F7C3 {
        state Fire {
            Fire: TODO
        }

        state THL {
            THL: TODO
        }

        state ABC {
            ABC: TODO
        }

    }
}

@enduml
