@startuml medical key questions (id=Medical_Key_Questions)
hide empty description

    state Medical_Key_Questions as "Medical Key Questions" #C3F7C3 {

        state Breathing as "Breathing normally?" #FFF5C3
        Breathing: - First Medical Key Question
        Breathing: - Has T-CPR and Immediate Disposition\nas edge-cases that other question lack
        state Breathing_choice <<choice>>

        state Next_Question as "Next Question" #FFF5C3
        Next_Question: repeat until all quesitons answered
        Next_Question: yes/no descision might change

        state Known_Symptoms as "Known\nSymptoms" #C3F7C3
        state RD1 as "RD1" #C3F7C3
        state RD2 as "RD2" #C3F7C3

        [*] --> Breathing
        Breathing --> Breathing_choice
        Breathing_choice -right-> Next_Question: Yes [deny symptom]
        Breathing_choice --> RD1: No [confirm symptom]

        Next_Question --> Next_Question : loop

        Known_Symptoms --> RD1: non‑critical
        RD1 --> Known_Symptoms: clarifying\nquestion

        Known_Symptoms --> RD2: other critical\nsymptom

        RD2 --> [*]
        RD1 --> [*]: non‑critical
    }

@enduml
