@startuml medical (id=Medical)
hide empty description

state Medical_Emergency as "Medical Emergency" #11b34f {
    !include medical_key_questions.puml

    state urgency_choice <<choice>>

    state first_aid_needed as "First Aid\nneeded"  #C3F7C3
    state first_aid_algo as "First Aid\nAlgorithm"  #C3DBFF
    state first_aid_fork <<fork>>

    state tcpr_fork <<fork>>
    state tcpr_algo as "T-CPR\nAlgorithm" #C3DBFF
    state tcpr_needed as "T-CPR\nneeded" #C3F7C3


    Known_Symptoms --> tcpr_needed: agonal\nrespiration

    [*] --> urgency_choice: parse what utterance
    urgency_choice --> Medical_Key_Questions: no urgent measures yet
    urgency_choice --> tcpr_needed: cardiac arrest
    urgency_choice --> first_aid_needed: heavy injury, heavy accident,\nsuffocation, cyanosis

    tcpr_needed --> tcpr_fork: start T-CPR and\n send ambulance
    first_aid_needed --> first_aid_fork: start First Aid and\n send ambulance

    tcpr_fork --> tcpr_algo
    tcpr_fork --> [*]

    first_aid_fork --> first_aid_algo: if exists
    first_aid_fork --> [*]

    Medical_Key_Questions -left-> [*]
}

' state Completion as "Completion of Data" #C3DBFF
state NumberPatients as "Number of Patients" #C3F7C3
NumberPatients: Completion of data

state Disposition as "Disposition" #C3DBFF

' Medical_Emergency --> Completion
Medical_Emergency --> NumberPatients: ask for number of patients
NumberPatients --> Disposition: inform about taken measures

Disposition --> [*]: end call

@enduml
